2022-09-23 20:55:05,684 ERROR: Exception on /user/Felipe [GET] [in C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\cce\project\microblog\app\routes.py", line 133, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\cce\project\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\cce\project\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\cce\project\microblog\app\templates\base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\cce\project\microblog\app\templates\user.html", line 35, in block 'app_content'
    {% include '_post.html' %}
  File "C:\Users\cce\project\microblog\app\templates\_post.html", line 9, in top-level template code
    {{ _('%(username)s said %(when)s',
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\jinja2\ext.py", line 167, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\jinja2\ext.py", line 173, in gettext
    rv = __context.call(func, __string)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 109, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 209, in get_translations
    return get_domain().get_translations()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 554, in get_translations
    locale = get_locale()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 230, in get_locale
    locale = Locale.parse(rv)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\babel\core.py", line 267, in parse
    parts = parse_locale(identifier, sep=sep)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\babel\core.py", line 1099, in parse_locale
    raise ValueError('expected only letters, got %r' % lang)
ValueError: expected only letters, got 'pt-br'
2022-09-23 20:55:25,500 ERROR: Exception on /explore [GET] [in C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\cce\project\microblog\app\routes.py", line 51, in explore
    return render_template('index.html', title='Explore', posts=posts.items,
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\cce\project\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\cce\project\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\cce\project\microblog\app\templates\base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\cce\project\microblog\app\templates\index.html", line 4, in block 'app_content'
    <h1>{{ _('Hi, %(username)s!', current_user.username) }}!</h1>
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\jinja2\ext.py", line 167, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
TypeError: _make_new_gettext.<locals>.gettext() takes 2 positional arguments but 3 were given
2022-09-23 20:55:27,840 ERROR: Exception on /index [GET] [in C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_login\login_manager.py", line 180, in unauthorized
    if self.login_message:
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\speaklater.py", line 24, in __len__
    return len(str(self))
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\speaklater.py", line 21, in __str__
    return str(self._func(*self._args, **self._kwargs))
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 689, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 586, in gettext
    t = self.get_translations()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 554, in get_translations
    locale = get_locale()
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 230, in get_locale
    locale = Locale.parse(rv)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\babel\core.py", line 267, in parse
    parts = parse_locale(identifier, sep=sep)
  File "C:\Users\cce\project\microblog\venv\lib\site-packages\babel\core.py", line 1099, in parse_locale
    raise ValueError('expected only letters, got %r' % lang)
ValueError: expected only letters, got 'pt-br'
